// Stable, app-wide codes
const CODES = {
  OK: "OK",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Auth/login
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Dataverse-specific
  DV_FORBIDDEN: "DV_FORBIDDEN",
  DV_BAD_PAYLOAD: "DV_BAD_PAYLOAD",
  DV_SCHEMA_MISMATCH: "DV_SCHEMA_MISMATCH",
  DV_FIELD_SECURED: "DV_FIELD_SECURED",
};

const CODE_TO_HTTP = {
  BAD_REQUEST: 400,
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_MISSING: 401,
  TOKEN_INVALID: 401,
  TOKEN_EXPIRED: 401,
  FORBIDDEN: 403,
  DV_FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  DV_BAD_PAYLOAD: 400,
  DV_SCHEMA_MISMATCH: 400,
  DV_FIELD_SECURED: 403,
  INTERNAL_ERROR: 500,
};

module.exports = { CODES, CODE_TO_HTTP };
